@startuml
class FormAddUserToGroup <<partial>> {
    - components : System.ComponentModel.IContainer = null
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
    - label1 : Label
    - usernameTextBox : TextBox
    - addButton : Button
}
@enduml
