@startuml
class User {
    + UserId : int <<get>> <<set>>
    + Username : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + FirstName : string <<get>> <<set>>
    + LastName : string <<get>> <<set>>
    + UserType : int <<get>> <<set>>
    + IdCountry : int <<get>> <<set>>
    + CreationDate : DateTime <<get>> <<set>>
}
@enduml
