@startuml
!include .\\BillSplitter.DataAccess\ConnectionFactory.puml
!include .\\BillSplitter.UI\Program.puml
!include .\\BillSplitter.DataAccess\Consts\StoredProcedures.puml
!include .\\BillSplitter.DataAccess\Enums\AddGroupResult.puml
!include .\\BillSplitter.DataAccess\Enums\LoginResult.puml
!include .\\BillSplitter.DataAccess\Models\Balance.puml
!include .\\BillSplitter.DataAccess\Models\Group.puml
!include .\\BillSplitter.DataAccess\Models\Receipt.puml
!include .\\BillSplitter.DataAccess\Models\User.puml
!include .\\BillSplitter.DataAccess\Models\UserAmount.puml
!include .\\BillSplitter.DataAccess\Properties\Resources.Designer.puml
!include .\\BillSplitter.UI\Forms\FormAddNewGroup.puml
!include .\\BillSplitter.UI\Forms\FormAddNewGroup.Designer.puml
!include .\\BillSplitter.UI\Forms\FormAddReceipt.puml
!include .\\BillSplitter.UI\Forms\FormAddReceipt.Designer.puml
!include .\\BillSplitter.UI\Forms\FormAddUserToGroup.puml
!include .\\BillSplitter.UI\Forms\FormAddUserToGroup.Designer.puml
!include .\\BillSplitter.UI\Forms\FormGroup.puml
!include .\\BillSplitter.UI\Forms\FormGroup.Designer.puml
!include .\\BillSplitter.UI\Forms\FormGroupOwner.puml
!include .\\BillSplitter.UI\Forms\FormGroupOwner.Designer.puml
!include .\\BillSplitter.UI\Forms\FormLogin.puml
!include .\\BillSplitter.UI\Forms\FormLogin.Designer.puml
!include .\\BillSplitter.UI\Forms\FormReceiptDetails.puml
!include .\\BillSplitter.UI\Forms\FormReceiptDetails.Designer.puml
!include .\\BillSplitter.UI\Forms\FormUserGroups.puml
!include .\\BillSplitter.UI\Forms\FormUserGroups.Designer.puml
!include .\\BillSplitter.DataAccess\Repositories\Implementations\AddNewGroupRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Implementations\AddReceiptRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Implementations\AddUserToGroupRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Implementations\GroupOwnerRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Implementations\GroupRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Implementations\LoginRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Implementations\ReceiptDetailsRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Implementations\UserGroupsRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Interfaces\IAddNewGroupRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Interfaces\IAddReceiptRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Interfaces\IAddUserToGroupRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Interfaces\IGroupOwnerRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Interfaces\IGroupRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Interfaces\ILoginRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Interfaces\IReceiptDetailsRepository.puml
!include .\\BillSplitter.DataAccess\Repositories\Interfaces\IUserGroupsRepository.puml
!include .\\BillSplitter.DataAccess\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\BillSplitter.DataAccess\obj\Debug\net6.0\BillSplitter.DataAccess.AssemblyInfo.puml
!include .\\BillSplitter.DataAccess\obj\Debug\net6.0\BillSplitter.DataAccess.GlobalUsings.g.puml
!include .\\BillSplitter.UI\obj\Debug\net6.0-windows\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\BillSplitter.UI\obj\Debug\net6.0-windows\BillSplitter.AssemblyInfo.puml
!include .\\BillSplitter.UI\obj\Debug\net6.0-windows\BillSplitter.GlobalUsings.g.puml
!include .\\BillSplitter.UI\obj\Debug\net6.0-windows\BillSplitter.UI.AssemblyInfo.puml
!include .\\BillSplitter.UI\obj\Debug\net6.0-windows\BillSplitter.UI.GlobalUsings.g.puml
@enduml
