@startuml
interface IAddReceiptRepository {
    TryAddReceipt(userId:int, groupId:int, amount:decimal, name:string) : int
    AddUserToReceipt(userId:int, receiptId:int, amount:decimal) : bool
}
@enduml
